<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="CustomerG.txt" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="CustomerG.txt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InterviewRound3.Domain\InterviewRound3.Domain.csproj" />
    <ProjectReference Include="..\InterviewRound3.Writer\InterviewRound3.Writer.csproj" />
  </ItemGroup>

</Project>
