<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>TRACE;READ_FILE_FROM_DISK</DefineConstants>
  </PropertyGroup>

  <Choose>
    <When Condition="$(DefineConstants.Contains('READ_FILE_FROM_DISK'))">
      <ItemGroup>
        <EmbeddedResource Include="CustomerG.txt">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </EmbeddedResource>
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <EmbeddedResource Include="CustomerG.txt" />
      </ItemGroup>
    </Otherwise>
  </Choose>

  <ItemGroup>
    <ProjectReference Include="..\InterviewRound3.Domain\InterviewRound3.Domain.csproj" />
    <ProjectReference Include="..\InterviewRound3.Writer\InterviewRound3.Writer.csproj" />
  </ItemGroup>

</Project>
