@startuml

'01232020Jamie
'BEVGTTKYGDGJHGTFBNGDVZJGDIPXVS
'CANFDNSKAVOUXSCGSYBHQYHNMDQOBL
'FRZNQQNPSESCHIMIXOUHNAWLXRZEPT
'BEVGZYUFGNIHDCZIPWLZJLPDSGNEAH

class ProductKeys {
    ProductType[] Keys
    --
    +AddKey(ProductType productType)
}

class PurchaseEntity {
    DateTime Timestamp
    string Customer
    BarcodeValue[] Barcodes
    --
    {static} +Task<PurchaseEntity> CreateFromStream(Stream stream) <<async>>
}
note left
Timestamp is in the format MMDDYYYY
    It is a char[8] in the file.
end note

class PurchaseAggregate {
    PurchaseEntity Purchase
    --
    +PurchaseAggregate(PurchaseEntity purchase) <<constructor>>
    +UniqueId[] GetUniqueIds()
    +BarcodeValue GetMostCommonProductByType()
    +ProductSubtype[] GetProductSubtypes(ProductType productType)
}

class "char[4]" as char4
class "char[6]" as char6
class "char[20]" as char20

ProductType <|-- char4
ProductSubtype <|-- char6
UniqueId <|-- char20
note right of ProductSubtype
Each of these char[] types is a string,
    this is just to denote the size.
end note

class BarcodeValue {
    ProductType ProductType
    ProductSubtype ProductSubtype
    UniqueId Id
}

BarcodeValue *-- ProductType : has
BarcodeValue *-- ProductSubtype : has
BarcodeValue *-- UniqueId : has

ProductKeys *-- ProductType : has many

PurchaseEntity *- BarcodeValue : has many

PurchaseAggregate *-- PurchaseEntity : has many

@enduml